# Generated by Django 5.0.1 on 2025-09-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0002_filepermissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filepermissions",
            name="permissions",
            field=models.CharField(choices=[("read", "Read"), ("read_write", "Read / Write")], max_length=10),
        ),
    ]
